=== Sneha213/XML-WorkSpace/XML-XSD_WorkSpace-2/employees.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--employees.xsd file
  Author: Sneha Patel(000783907)
  Title of Assignment: Correct the attached xsd for the accompanied employees.xml file.  
                       The xsd must be well formed, formatted nicely, have comments, have an annotation, and properly validate the employees.xml file.  
                       Business rules must followed while creating the xsd file. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<!-- Annotations/Documention are machine readable comments.  They are used quite
			a bit for documentation for users (particularly in web service/rest APIs -->
	<xs:annotation>
		<xs:documentation>Comment describing your root element</xs:documentation>
	</xs:annotation>
	<!-- one and only one employees element as complex-type-->
	<xs:element name="employees">
		<xs:complexType>
			<xs:sequence>
				<!---	employees element with one and more than one employee elements as complex-type-->
				<xs:element name="employee" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<!---	employee element has one and only one expertise element -->
							<xs:element name="expertise" type="xs:string" maxOccurs="1"/>
							<!--employee element has one to many consultedClient child elements-->
							<xs:element name="consultedClient" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="durationInMonths" type="xs:positiveInteger" use="optional"/>
									<xs:attribute name="position" use="required">
										<!--Positive element has enumerations-->
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="teamLead"/>
												<xs:enumeration value="manager"/>
												<xs:enumeration value="programmer"/>
												<xs:enumeration value="analyst"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<!--- DurationInMonths has a positive integer type and is optional -->
									<!--Position is required element-->
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						
						<!---	employee element that have name, sinNumber and sex attributes and 
                        it's all are required except for birthdate-->
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="birthdate" type="xs:string" use="optional"/>
						<xs:attribute name="sinNumber" type="xs:string" use="required"/>
						<xs:attribute name="sex" use="required">
							<!--sex element has enumerations-->
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="male"/>
									<xs:enumeration value="female"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>						
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Sneha213/XML-WorkSpace/XML-XSD_WorkSpace-2/employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--employees.xml file_Sneha Patel(000783907)-->

<!--employees is complex-type element because it has child i.e. employee-->
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="employees.xsd">
    
    <!--employee is complex-type element because it has child and attributes -->
	<employee name="Jonathan Smithe" birthdate="1949" sinNumber="384 288 981" sex="male">
	    
        <!--expertise is simple-type element because it doesnot have child or attribute -->
		<expertise>Java, XML, UML, Project management</expertise>
		
        <!--consultedClient is complex-type element because it has child and attributes-->
		<consultedClient name="Enmax" durationInMonths="39" position="manager"/>
		<consultedClient name="Enbridge" durationInMonths="12" position="teamLead"/>
		<consultedClient name="City Of Calgary" durationInMonths="26" position="programmer"/>
	</employee>
	
	<!--Duplication of employee and it's child with attributes-->
	<employee name="Shiela Knox" birthdate="1970" sinNumber="284 401 483" sex="female">
		<expertise>C#, C++, XML, Perl, Apache Tomcat, Oracle, MySQL</expertise>
		<consultedClient name="Logitech" position="programmer"/>
		<consultedClient name="Husky" durationInMonths="16" position="programmer"/>
		<consultedClient name="Northern Oil" durationInMonths="20" position="analyst"/>
		<consultedClient name="Mark's Work Wearhouse" durationInMonths="24" position="programmer"/>
	</employee>
	
</employees>
